"""empty message

Revision ID: dc1da4949dbc
Revises: ee09a58981bb
Create Date: 2022-03-27 12:36:17.708748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1da4949dbc'
down_revision = 'ee09a58981bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(), nullable=False),
    sa.Column('disease_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_table('contact_log',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('user_disease',
    sa.Column('user_disease_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_disease_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_disease')
    op.drop_table('contact_log')
    op.drop_table('disease')
    # ### end Alembic commands ###
